apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hipster-ns.yaml
  - adservice.yaml
  - cartservice.yaml
  - checkoutservice.yaml
  - currencyservice.yaml
  - emailservice.yaml
  - frontendservice.yaml
  - loadgenerator.yaml
  - paymentservice.yaml
  - productcatalogservice.yaml
  - recommendationservice.yaml
  - shippingservice.yaml
  - hipster-ingress.yaml
